export const systems = [
    { id: 'case', name: 'Frame & rails', color: '#78716c' },
    { id: 'keyboard', name: 'Key & balance', color: '#bb935e' },
    { id: 'action', name: 'Escapement & repetition', color: '#cd6565' },
    { id: 'frame', name: 'Hammer assembly', color: '#c4a46a' },
    { id: 'resonance', name: 'Damper assembly', color: '#4d9377' },
    { id: 'strings', name: 'String', color: '#a4adb1' },
];
const definitions = [
    ['base', 'Demonstration base', 'case', 'A stable display plinth supports this enlarged single-note teaching model.', 'Hardwood', 'Support', ['keyframe']],
    ['keyframe', 'Key frame', 'case', 'The wooden frame supports the balance, front, and back rails beneath the key.', 'Hardwood', 'Structure', ['balance-rail', 'front-rail', 'back-rail']],
    ['key', 'Key lever', 'keyboard', 'Pressing the front of the key raises its rear, driving the capstan and lifting the damper underlever.', 'Seasoned wood', 'Player input', ['keytop', 'capstan', 'balance-pin']],
    ['keytop', 'Keytop', 'keyboard', 'The smooth playing surface covers the front end of the wooden key.', 'Synthetic ivory', 'Playing surface', ['key']],
    ['balance-rail', 'Balance rail', 'keyboard', 'This central rail supports the fulcrum about which the key rocks.', 'Hardwood', 'Key pivot support', ['balance-pin', 'balance-felt']],
    ['balance-pin', 'Balance pin', 'keyboard', 'A polished pin guides the key at its balance point.', 'Steel', 'Guidance', ['key', 'balance-felt']],
    ['balance-felt', 'Balance rail punching', 'keyboard', 'A felt washer cushions the key at its pivot.', 'Wool felt', 'Cushioning', ['balance-pin']],
    ['front-rail', 'Front rail & guide pin', 'keyboard', 'The front rail and pin guide the playing end of the key.', 'Wood / steel', 'Guidance', ['front-felt', 'key']],
    ['front-felt', 'Front rail punching', 'keyboard', 'This felt pad cushions the key at the bottom of its travel.', 'Wool felt', 'Key dip stop', ['front-rail']],
    ['back-rail', 'Back rail cloth', 'keyboard', 'The rear of the released key rests on this soft cloth.', 'Wool felt', 'Quiet return', ['keyframe', 'key']],
    ['capstan', 'Capstan screw', 'action', 'The adjustable brass capstan transfers the rising key motion to the wippen heel.', 'Brass', 'Motion transfer', ['key', 'wippen-heel']],
    ['wippen-heel', 'Wippen heel', 'action', 'A cushioned heel receives the capstan and raises the wippen assembly.', 'Wood / felt', 'Contact', ['wippen', 'capstan']],
    ['wippen', 'Wippen', 'action', 'This pivoted lever carries the jack and repetition lever as the key rises.', 'Hardwood', 'Action drive', ['jack', 'repetition', 'wippen-flange']],
    ['wippen-flange', 'Wippen flange', 'action', 'A pinned wooden flange anchors the wippen to the action rail.', 'Wood / center pin', 'Pivot', ['wippen', 'action-rail']],
    ['jack', 'Jack', 'action', 'The jack pushes the hammer knuckle upward, then escapes from beneath it near the end of the keystroke.', 'Hardwood', 'Escapement', ['knuckle', 'let-off', 'wippen']],
    ['repetition', 'Repetition lever', 'action', 'The spring-supported repetition lever catches and supports the knuckle after the hammer rebounds, helping prepare a repeated strike.', 'Hardwood', 'Rapid repetition', ['knuckle', 'spring', 'drop-screw']],
    ['spring', 'Repetition spring', 'action', 'A fine wire spring helps return the repetition lever and jack to their working positions.', 'Spring steel', 'Return force', ['repetition', 'jack']],
    ['let-off', 'Let-off button & screw', 'action', 'The jack tender contacts this adjustable button so the jack trips before the hammer reaches the string.', 'Wood / felt / brass', 'Escapement regulation', ['jack']],
    ['drop-screw', 'Drop screw', 'action', 'This screw limits the rise of the repetition lever during escapement.', 'Steel / felt', 'Repetition regulation', ['repetition']],
    ['action-rail', 'Action bracket & rail', 'case', 'The metal bracket and wooden rail hold the action pivots in alignment.', 'Cast metal / hardwood', 'Structure', ['wippen-flange', 'hammer-flange']],
    ['hammer-flange', 'Hammer flange', 'frame', 'The pinned flange provides the hammer shank pivot.', 'Hardwood / center pin', 'Hammer pivot', ['shank', 'action-rail']],
    ['shank', 'Hammer shank', 'frame', 'A slender wooden shank swings the hammer head toward the string.', 'Hardwood', 'Motion transfer', ['hammer', 'knuckle']],
    ['hammer', 'Hammer head', 'frame', 'Compressed felt surrounding the wooden molding strikes the string and rebounds immediately.', 'Wool felt / wood', 'String excitation', ['shank', 'string', 'backcheck']],
    ['knuckle', 'Hammer knuckle', 'frame', 'A leather-covered roller beneath the shank receives the jack and repetition lever.', 'Wood / leather', 'Action contact', ['jack', 'repetition', 'shank']],
    ['hammer-rest', 'Hammer rest cushion', 'frame', 'A soft rest cushions the hammer assembly when the key is released.', 'Wood / wool felt', 'Quiet return', ['hammer']],
    ['backcheck', 'Backcheck & wire', 'frame', 'The leather-covered backcheck catches the rebounding hammer while the key remains depressed.', 'Wood / leather / steel', 'Rebound control', ['hammer', 'key']],
    ['damper-head', 'Damper head & felt', 'resonance', 'The felt rests on the string to stop its vibration. Playing the key lifts it clear.', 'Wood / wool felt', 'Sound control', ['damper-wire', 'string']],
    ['damper-wire', 'Damper wire', 'resonance', 'The wire connects the damper head to its underlever below.', 'Steel', 'Motion transfer', ['damper-underlever', 'damper-guide']],
    ['damper-guide', 'Damper guide rail', 'resonance', 'A bushed guide keeps the damper wire moving vertically.', 'Hardwood / felt', 'Guidance', ['damper-wire']],
    ['damper-underlever', 'Damper underlever', 'resonance', 'The rear of the key lifts this weighted lever, raising the damper wire and head.', 'Wood / metal', 'Damper lift', ['key', 'damper-wire']],
    ['string', 'Piano string', 'strings', 'The hammer excites the tensioned string after the damper lifts clear.', 'Steel', 'Vibration', ['hammer', 'damper-head']],
];
export const parts = definitions.map(([id, name, system, description, material, role, related], i) => ({ id, name, system, description, material, role, related, number: String(i + 1).padStart(2, '0') }));
