export const systems = [
    { id: 'case', name: 'Case & lid', color: '#4b4b4b' },
    { id: 'keyboard', name: 'Keyboard', color: '#6b7280' },
    { id: 'action', name: 'Action & dampers', color: '#ff4b4b' },
    { id: 'strings', name: 'Strings & tuning', color: '#ffc800' },
    { id: 'resonance', name: 'Soundboard', color: '#ff9600' },
    { id: 'frame', name: 'Iron frame', color: '#78716c' },
    { id: 'pedals', name: 'Pedals & supports', color: '#1cb0f6' },
];

// A teaching model: dimensions and component arrangements are illustrative.
// References: Yamaha Musical Instrument Guide, Structure / Parts and Action.
export const parts = [
    ['rim', 'Bent rim', 'case', 'The curved, laminated wooden case gives the grand its silhouette and supports the soundboard and plate.', 'Laminated hardwood', 'Structure', ['soundboard', 'plate']],
    ['underframe', 'Wooden underframe', 'case', 'Heavy wooden posts brace the underside of the soundboard and connect the curved rim to the front bed. The enclosed wooden belly separates the strings from the space below the piano.', 'Structural timber', 'Belly support', ['soundboard', 'ribs', 'keybed', 'rim']],
    ['lid', 'Grand lid', 'case', 'The main lid covers the strings. Its hinged front leaf folds back on top when open, then unfolds over the music desk when closed. The music rack folds flat underneath.', 'Polished hardwood', 'Projection', ['prop', 'rim']],
    ['prop', 'Lid prop', 'case', 'A wooden support holds the lid at its open position.', 'Hardwood', 'Support', ['lid']],
    ['desk', 'Music rack', 'case', 'The gently tilted rack holds sheet music above the keyboard. Its shaped upper edge, lower ledge, and supporting desk sit in the open front section ahead of the main lid.', 'Finished hardwood', 'Sheet music support', ['fallboard', 'lid']],
    ['fallboard', 'Fallboard', 'case', 'The fallboard is the front panel immediately behind the keys. It protects the keyboard when folded down; it is shown in its open position here, separate from the curved rim.', 'Finished hardwood', 'Key protection', ['white-keys', 'black-keys']],
    ['keybed', 'Key bed', 'case', 'A rigid platform supports the keyboard and action assembly at the front of the piano.', 'Hardwood', 'Structure', ['key-levers', 'rim']],
    ['white-keys', 'White keys', 'keyboard', 'The 52 white keys play the natural notes. Together with the black keys they span A0 to C8.', 'Wood / synthetic tops', 'Player input', ['black-keys', 'key-levers']],
    ['black-keys', 'Black keys', 'keyboard', 'The 36 raised black keys form repeating groups of two and three, providing the sharps and flats.', 'Wood / dark keytops', 'Player input', ['white-keys', 'key-levers']],
    ['key-levers', 'Key levers', 'keyboard', 'Each key is a balanced lever. Depressing its front raises the rear to drive the action above it.', 'Seasoned wood', 'Motion transfer', ['balance-rail', 'wippens']],
    ['balance-rail', 'Balance rail', 'keyboard', 'The keys pivot around pins on this rail. Felt bushings and washers help guide their movement quietly.', 'Wood / metal / felt', 'Key pivot', ['key-levers']],
    ['hammers', 'Hammer heads', 'action', 'Felt-covered hammers strike the strings and immediately rebound, allowing them to vibrate freely.', 'Wool felt / wood', 'Excitation', ['shanks', 'treble-strings']],
    ['shanks', 'Hammer shanks', 'action', 'Slender wooden shafts carry the hammer heads through an arc toward the strings.', 'Hardwood', 'Motion transfer', ['hammers', 'wippens']],
    ['wippens', 'Wippens & jacks', 'action', 'These lever assemblies transmit key motion to the hammer. The jack escapes before impact so the hammer can rebound.', 'Wood / felt / metal', 'Escapement', ['key-levers', 'hammers']],
    ['dampers', 'Damper heads', 'action', 'Felt pads stop string vibration when a key is released. The highest treble strings normally have no dampers.', 'Wood / wool felt', 'Sound control', ['damper-rail', 'sustain']],
    ['damper-rail', 'Damper lift rail', 'action', 'The sustain pedal operates this rail to lift the dampers together, letting notes continue to ring.', 'Hardwood / metal', 'Damper control', ['dampers', 'sustain']],
    ['bass-strings', 'Bass strings', 'strings', 'Copper winding adds mass to the low strings so they can produce deep notes within the length of the case. They cross above the other strings.', 'Copper-wound steel', 'Low register', ['bass-bridge', 'tuning-pins']],
    ['treble-strings', 'Middle & treble strings', 'strings', 'Steel strings become shorter toward the treble. Multiple strings tuned in unison give most notes their characteristic fullness.', 'High-carbon steel', 'Middle / high register', ['treble-bridge', 'tuning-pins']],
    ['tuning-pins', 'Tuning pins', 'strings', 'A technician turns these tightly seated pins to adjust string tension and pitch.', 'Steel', 'Pitch adjustment', ['pinblock', 'bass-strings']],
    ['hitch-pins', 'Hitch pins', 'strings', 'These anchors secure the far ends of the strings to the plate.', 'Steel', 'String anchoring', ['plate', 'treble-strings']],
    ['pinblock', 'Pinblock', 'strings', 'Layers of hardwood grip the tuning pins firmly while allowing precise tuning adjustments.', 'Laminated hardwood', 'Tuning stability', ['tuning-pins', 'plate']],
    ['soundboard', 'Soundboard', 'resonance', 'This thin, broad wooden surface receives vibration from the bridges and sets a much larger area of air in motion.', 'Spruce', 'Sound radiation', ['ribs', 'treble-bridge']],
    ['ribs', 'Soundboard ribs', 'resonance', 'Wooden ribs reinforce the underside of the soundboard and help maintain its gently crowned shape.', 'Spruce', 'Reinforcement', ['soundboard']],
    ['bass-bridge', 'Bass bridge', 'resonance', 'The bass strings bear on this wooden bridge, which transmits their vibration to the soundboard.', 'Hardwood', 'Vibration transfer', ['bass-strings', 'soundboard']],
    ['treble-bridge', 'Long bridge', 'resonance', 'This curved bridge couples the middle and treble strings to the soundboard and defines one end of their speaking length.', 'Hardwood', 'Vibration transfer', ['treble-strings', 'soundboard']],
    ['plate', 'Cast-iron plate', 'frame', 'The metal frame carries the combined tension of the strings. Its openings leave room for the soundboard beneath.', 'Cast iron', 'Tension support', ['braces', 'hitch-pins']],
    ['braces', 'Plate struts', 'frame', 'Heavy reinforcing members distribute the string load across the cast-iron frame.', 'Cast iron', 'Reinforcement', ['plate']],
    ['legs', 'Piano legs', 'pedals', 'Three legs support the piano: two near the keyboard and one at the curved tail.', 'Hardwood', 'Weight support', ['casters', 'rim']],
    ['casters', 'Brass casters', 'pedals', 'Wheels beneath the legs allow careful repositioning of the piano.', 'Brass / steel', 'Mobility', ['legs']],
    ['lyre', 'Pedal lyre', 'pedals', 'The suspended support houses the pedals and their connecting rods beneath the keyboard.', 'Wood / metal', 'Pedal support', ['sustain', 'sostenuto', 'una-corda']],
    ['una-corda', 'Una corda pedal', 'pedals', 'The left pedal shifts the grand action sideways, changing the hammer contact with the strings and softening the tone.', 'Brass', 'Tone color', ['wippens', 'hammers']],
    ['sostenuto', 'Sostenuto pedal', 'pedals', 'The middle pedal holds up the dampers that are already raised when it is pressed, sustaining selected notes.', 'Brass', 'Selective sustain', ['dampers']],
    ['sustain', 'Sustain pedal', 'pedals', 'The right pedal lifts the dampers together, allowing strings to keep vibrating after the keys are released.', 'Brass', 'Sustain', ['damper-rail', 'dampers']],
].map(([id, name, system, description, material, role, related], index) => ({ id, name, system, description, material, role, related, number: String(index + 1).padStart(2, '0') }));
